# Generated by Django 3.1.6 on 2021-02-08 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('gender', models.CharField(choices=[('1', '男性'), ('2', '女性'), ('3', 'その他')], default='1', max_length=1, verbose_name='性別')),
                ('duties', models.CharField(choices=[('1', 'リーダー'), ('2', 'ベテラン'), ('3', '新人')], default='3', max_length=1, verbose_name='役職')),
            ],
        ),
    ]
